name: External Event Trigger

on:
  push:
    branches:
      - main


jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Message
        run: echo "Workflow triggered by an external event!"

  dispatch-event:
    runs-on: ubuntu-latest

  
    needs: trigger-job

    steps:
      - name: Dispatch Repository Event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json"\
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
            --data '{"event_type": "my-custom-event"}'\
            "https://api.github.com/repos/${{ github.repository }}/dispatches"
